use inkwell::values::BasicValue;
use inkwell::IntPredicate;

use super::super::{CodeGen, llvm_err};

impl<'ctx> CodeGen<'ctx> {
    pub(super) fn define_list_basics(&self) -> Result<(), String> {
        let i64 = self.i64_ty();
        let ptr = self.ptr_ty();
        let list_ty = self.list_type;
        let b1 = self.bool_ty();

        let malloc_rc_fn = self.module.get_function("atomic_malloc_rc").unwrap();
        let realloc_fn = self.module.get_function("realloc").unwrap();

        let list_create_fn = self.module.add_function("atomic_list_create", list_ty.fn_type(&[i64.into()], false), None);
        let entry = self.context.append_basic_block(list_create_fn, "entry");
        self.builder.position_at_end(entry);
        let cap = list_create_fn.get_first_param().unwrap().into_int_value();
        let elem_size = i64.const_int(16, false);
        let data_size = self.builder.build_int_mul(cap, elem_size, "data_size").map_err(llvm_err)?;
        let data = self.builder.build_call(malloc_rc_fn, &[data_size.into()], "data").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_pointer_value();
        let zero = i64.const_int(0, false);
        let undef = list_ty.get_undef();
        let r1 = self.builder.build_insert_value(undef, data, 0, "r1").map_err(llvm_err)?;
        let r2 = self.builder.build_insert_value(r1, zero, 1, "r2").map_err(llvm_err)?;
        let r3 = self.builder.build_insert_value(r2, cap, 2, "r3").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&r3));

        // ---- atomic_list_push({ptr, i64, i64}, {i64, ptr}) -> {ptr, i64, i64} ----
        let list_push_fn = self.module.add_function("atomic_list_push", list_ty.fn_type(&[list_ty.into(), self.string_type.into()], false), None);
        let lp_entry = self.context.append_basic_block(list_push_fn, "entry");
        let lp_grow = self.context.append_basic_block(list_push_fn, "grow");
        let lp_done = self.context.append_basic_block(list_push_fn, "done");
        self.builder.position_at_end(lp_entry);
        let list = list_push_fn.get_first_param().unwrap().into_struct_value();
        let elem = list_push_fn.get_nth_param(1).unwrap().into_struct_value();
        let data_ptr = self.builder.build_extract_value(list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let len = self.builder.build_extract_value(list, 1, "len").map_err(llvm_err)?.into_int_value();
        let cap = self.builder.build_extract_value(list, 2, "cap").map_err(llvm_err)?.into_int_value();
        let one = i64.const_int(1, false);
        let need_grow = self.builder.build_int_compare(IntPredicate::SGE, len, cap, "need_grow").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(need_grow, lp_grow, lp_done);

        self.builder.position_at_end(lp_grow);
        let min_cap = i64.const_int(4, false);
        let cap_small = self.builder.build_int_compare(IntPredicate::SLT, cap, min_cap, "cap_small").map_err(llvm_err)?;
        let cap2x = self.builder.build_int_mul(cap, i64.const_int(2, false), "cap2x").map_err(llvm_err)?;
        let new_cap = self.builder.build_select(cap_small, min_cap, cap2x, "new_cap").map_err(llvm_err)?.into_int_value();
        let data_size = self.builder.build_int_mul(new_cap, i64.const_int(16, false), "data_size").map_err(llvm_err)?;
        let total_size = self.builder.build_int_add(data_size, i64.const_int(8, false), "total_size").map_err(llvm_err)?;
        let data_int = self.builder.build_ptr_to_int(data_ptr, i64, "data_int").map_err(llvm_err)?;
        let rc_offset = i64.const_int(8, false);
        let orig_int = self.builder.build_int_sub(data_int, rc_offset, "orig_int").map_err(llvm_err)?;
        let orig_ptr = self.builder.build_int_to_ptr(orig_int, ptr, "orig_ptr").map_err(llvm_err)?;
        let new_orig = self.builder.build_call(realloc_fn, &[orig_ptr.into(), total_size.into()], "new_orig").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_pointer_value();
        let new_orig_int = self.builder.build_ptr_to_int(new_orig, i64, "new_orig_int").map_err(llvm_err)?;
        let new_data_int = self.builder.build_int_add(new_orig_int, rc_offset, "new_data_int").map_err(llvm_err)?;
        let new_data = self.builder.build_int_to_ptr(new_data_int, ptr, "new_data").map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(lp_done);

        self.builder.position_at_end(lp_done);
        let phi_data = self.builder.build_phi(ptr, "phi_data").map_err(llvm_err)?;
        phi_data.add_incoming(&[(&data_ptr, lp_entry), (&new_data, lp_grow)]);
        let phi_cap = self.builder.build_phi(i64, "phi_cap").map_err(llvm_err)?;
        phi_cap.add_incoming(&[(&cap, lp_entry), (&new_cap, lp_grow)]);
        let final_data = phi_data.as_basic_value().into_pointer_value();
        let final_cap = phi_cap.as_basic_value().into_int_value();
        let data_i8 = self.builder.build_pointer_cast(final_data, self.context.ptr_type(inkwell::AddressSpace::default()), "data_i8").map_err(llvm_err)?;
        let elem_ptr = unsafe { self.builder.build_gep(self.string_type, data_i8, &[len], "elem_ptr").map_err(llvm_err) }?;
        let _ = self.builder.build_store(elem_ptr, elem).map_err(llvm_err)?;
        let new_len = self.builder.build_int_add(len, one, "new_len").map_err(llvm_err)?;
        let undef = list_ty.get_undef();
        let r1 = self.builder.build_insert_value(undef, final_data, 0, "r1").map_err(llvm_err)?;
        let r2 = self.builder.build_insert_value(r1, new_len, 1, "r2").map_err(llvm_err)?;
        let r3 = self.builder.build_insert_value(r2, final_cap, 2, "r3").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&r3));

        // ---- atomic_list_get({ptr, i64, i64}, i64) -> {i64, ptr} ----
        let list_get_fn = self.module.add_function("atomic_list_get", self.string_type.fn_type(&[list_ty.into(), i64.into()], false), None);
        let entry = self.context.append_basic_block(list_get_fn, "entry");
        self.builder.position_at_end(entry);
        let list = list_get_fn.get_first_param().unwrap().into_struct_value();
        let idx = list_get_fn.get_nth_param(1).unwrap().into_int_value();
        let data_ptr = self.builder.build_extract_value(list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let data_i8 = self.builder.build_pointer_cast(data_ptr, self.context.ptr_type(inkwell::AddressSpace::default()), "data_i8").map_err(llvm_err)?;
        let elem_ptr = unsafe { self.builder.build_gep(self.string_type, data_i8, &[idx], "elem_ptr").map_err(llvm_err) }?;
        let val = self.builder.build_load(self.string_type, elem_ptr, "val").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&val));

        // ---- atomic_list_head({ptr, i64, i64}) -> {i64, ptr} ----
        let list_head_fn = self.module.add_function("atomic_list_head", self.string_type.fn_type(&[list_ty.into()], false), None);
        let entry = self.context.append_basic_block(list_head_fn, "entry");
        self.builder.position_at_end(entry);
        let lh_list = list_head_fn.get_first_param().unwrap().into_struct_value();
        let lh_len = self.builder.build_extract_value(lh_list, 1, "len").map_err(llvm_err)?.into_int_value();
        let lh_empty = self.builder.build_int_compare(IntPredicate::EQ, lh_len, i64.const_int(0, false), "empty").map_err(llvm_err)?;
        let lh_has = self.context.append_basic_block(list_head_fn, "has");
        let lh_none = self.context.append_basic_block(list_head_fn, "none");
        let _ = self.builder.build_conditional_branch(lh_empty, lh_none, lh_has);
        self.builder.position_at_end(lh_none);
        let lh_none_val = self.string_type.const_zero();
        let _ = self.builder.build_return(Some(&lh_none_val));
        self.builder.position_at_end(lh_has);
        let lh_data = self.builder.build_extract_value(lh_list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let lh_data_i8 = self.builder.build_pointer_cast(lh_data, self.context.ptr_type(inkwell::AddressSpace::default()), "data_i8").map_err(llvm_err)?;
        let lh_elem_ptr = unsafe { self.builder.build_gep(self.string_type, lh_data_i8, &[i64.const_int(0, false)], "elem_ptr").map_err(llvm_err) }?;
        let lh_val = self.builder.build_load(self.string_type, lh_elem_ptr, "val").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&lh_val));

        // ---- atomic_list_len({ptr, i64, i64}) -> i64 ----
        let list_len_fn = self.module.add_function("atomic_list_len", i64.fn_type(&[list_ty.into()], false), None);
        let entry = self.context.append_basic_block(list_len_fn, "entry");
        self.builder.position_at_end(entry);
        let list = list_len_fn.get_first_param().unwrap().into_struct_value();
        let len = self.builder.build_extract_value(list, 1, "len").map_err(llvm_err)?.into_int_value();
        let _ = self.builder.build_return(Some(&len));

        // ---- atomic_list_contains({ptr, i64, i64}, {i64, ptr}) -> i1 ----
        let lc_fn = self.module.add_function("atomic_list_contains",
            b1.fn_type(&[list_ty.into(), self.string_type.into()], false), None);
        let entry = self.context.append_basic_block(lc_fn, "entry");
        self.builder.position_at_end(entry);
        let lc_list = lc_fn.get_first_param().unwrap().into_struct_value();
        let lc_data = self.builder.build_extract_value(lc_list, 0, "lc_data").map_err(llvm_err)?.into_pointer_value();
        let lc_len = self.builder.build_extract_value(lc_list, 1, "lc_len").map_err(llvm_err)?.into_int_value();
        let lc_key = lc_fn.get_nth_param(1).unwrap().into_struct_value();
        let lc_key_tag = self.builder.build_extract_value(lc_key, 0, "lc_ktag").map_err(llvm_err)?.into_int_value();
        let lc_key_data = self.builder.build_extract_value(lc_key, 1, "lc_kdata").map_err(llvm_err)?.into_pointer_value();
        let lc_loop_bb = self.context.append_basic_block(lc_fn, "lc_loop");
        let lc_done_bb = self.context.append_basic_block(lc_fn, "lc_done");
        let _ = self.builder.build_unconditional_branch(lc_loop_bb);
        self.builder.position_at_end(lc_loop_bb);
        let lc_i = self.builder.build_phi(i64, "lc_i").map_err(llvm_err)?;
        let lc_data_ptr = self.builder.build_pointer_cast(lc_data, self.ptr_ty(), "lc_dp").map_err(llvm_err)?;
        let lc_elem_ptr = unsafe { self.builder.build_gep(self.string_type, lc_data_ptr, &[lc_i.as_basic_value().into_int_value()], "lc_ep").map_err(llvm_err) }?;
        let lc_elem = self.builder.build_load(self.string_type, lc_elem_ptr, "lc_elem").map_err(llvm_err)?;
        let lc_elem_ss = lc_elem.into_struct_value();
        let lc_elem_tag = self.builder.build_extract_value(lc_elem_ss, 0, "lc_etag").map_err(llvm_err)?.into_int_value();
        let lc_elem_data = self.builder.build_extract_value(lc_elem_ss, 1, "lc_edata").map_err(llvm_err)?.into_pointer_value();
        let tag_eq = self.builder.build_int_compare(IntPredicate::EQ, lc_elem_tag, lc_key_tag, "lc_teq").map_err(llvm_err)?;
        let lc_next_bb = self.context.append_basic_block(lc_fn, "lc_next");
        let lc_check_bb = self.context.append_basic_block(lc_fn, "lc_check");
        let _ = self.builder.build_conditional_branch(tag_eq, lc_check_bb, lc_next_bb);
        self.builder.position_at_end(lc_check_bb);
        let null_ptr = self.ptr_ty().const_zero();
        let ed_null = self.builder.build_int_compare(IntPredicate::EQ, lc_elem_data, null_ptr, "ed_null").map_err(llvm_err)?;
        let kd_null = self.builder.build_int_compare(IntPredicate::EQ, lc_key_data, null_ptr, "kd_null").map_err(llvm_err)?;
        let both_null = self.builder.build_and(ed_null, kd_null, "both_null").map_err(llvm_err)?;
        let lc_found_bb = self.context.append_basic_block(lc_fn, "lc_found");
        let lc_content_bb = self.context.append_basic_block(lc_fn, "lc_content");
        let _ = self.builder.build_conditional_branch(both_null, lc_found_bb, lc_content_bb);
        self.builder.position_at_end(lc_found_bb);
        let _ = self.builder.build_return(Some(&b1.const_int(1, false)));
        self.builder.position_at_end(lc_content_bb);
        let ed_nn = self.builder.build_not(ed_null, "ed_nn").map_err(llvm_err)?;
        let kd_nn = self.builder.build_not(kd_null, "kd_nn").map_err(llvm_err)?;
        let both_non_null = self.builder.build_and(ed_nn, kd_nn, "both_nn").map_err(llvm_err)?;
        let lc_str_check_bb = self.context.append_basic_block(lc_fn, "lc_str_check");
        let _ = self.builder.build_conditional_branch(both_non_null, lc_str_check_bb, lc_next_bb);
        self.builder.position_at_end(lc_str_check_bb);
        let str_eq_call = self.call_rt("atomic_string_eq", &[lc_elem_ss.as_basic_value_enum().into(), lc_key.as_basic_value_enum().into()])?;
        let str_eq_val = str_eq_call.try_as_basic_value().basic().unwrap().into_int_value();
        let lc_str_found_bb = self.context.append_basic_block(lc_fn, "lc_str_found");
        let _ = self.builder.build_conditional_branch(str_eq_val, lc_str_found_bb, lc_next_bb);
        self.builder.position_at_end(lc_str_found_bb);
        let _ = self.builder.build_return(Some(&b1.const_int(1, false)));
        self.builder.position_at_end(lc_next_bb);
        let lc_next_i = self.builder.build_int_add(lc_i.as_basic_value().into_int_value(), i64.const_int(1, false), "lc_ni").map_err(llvm_err)?;
        let lc_done = self.builder.build_int_compare(IntPredicate::SGE, lc_next_i, lc_len, "lc_done").map_err(llvm_err)?;
        let lc_next_block = self.builder.get_insert_block().unwrap();
        lc_i.add_incoming(&[(&i64.const_int(0, false), lc_fn.get_first_basic_block().unwrap()), (&lc_next_i, lc_next_block)]);
        let _ = self.builder.build_conditional_branch(lc_done, lc_done_bb, lc_loop_bb);
        self.builder.position_at_end(lc_done_bb);
        let _ = self.builder.build_return(Some(&b1.const_int(0, false)));

        // ---- atomic_list_reverse({ptr, i64, i64}) -> {ptr, i64, i64} ----
        let lr_fn = self.module.add_function("atomic_list_reverse", list_ty.fn_type(&[list_ty.into()], false), None);
        let lr_entry = self.context.append_basic_block(lr_fn, "entry");
        self.builder.position_at_end(lr_entry);
        let lr_list = lr_fn.get_first_param().unwrap().into_struct_value();
        let lr_data = self.builder.build_extract_value(lr_list, 0, "lr_data").map_err(llvm_err)?.into_pointer_value();
        let lr_len = self.builder.build_extract_value(lr_list, 1, "lr_len").map_err(llvm_err)?.into_int_value();
        let lr_cap = self.builder.build_extract_value(lr_list, 2, "lr_cap").map_err(llvm_err)?.into_int_value();
        let lr_new = self.builder.build_call(list_create_fn, &[lr_cap.into()], "lr_new").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("create failed")?;
        let lr_loop_bb = self.context.append_basic_block(lr_fn, "lr_loop");
        let lr_done_bb = self.context.append_basic_block(lr_fn, "lr_done");
        let _ = self.builder.build_unconditional_branch(lr_loop_bb);
        self.builder.position_at_end(lr_loop_bb);
        let lr_i = self.builder.build_phi(i64, "lr_i").map_err(llvm_err)?;
        let lr_list2 = self.builder.build_phi(list_ty, "lr_list2").map_err(llvm_err)?;
        let lr_rev_idx = self.builder.build_int_sub(lr_len, self.builder.build_int_add(lr_i.as_basic_value().into_int_value(), i64.const_int(1, false), "lr_plus1").map_err(llvm_err)?, "lr_rev_idx").map_err(llvm_err)?;
        let lr_dp = self.builder.build_pointer_cast(lr_data, self.ptr_ty(), "lr_dp").map_err(llvm_err)?;
        let lr_ep = unsafe { self.builder.build_gep(self.string_type, lr_dp, &[lr_rev_idx], "lr_ep").map_err(llvm_err) }?;
        let lr_elem = self.builder.build_load(self.string_type, lr_ep, "lr_elem").map_err(llvm_err)?;
        let lr_new2 = self.builder.build_call(list_push_fn, &[lr_list2.as_basic_value().into(), lr_elem.into()], "lr_push").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("push failed")?;
        let lr_next_i = self.builder.build_int_add(lr_i.as_basic_value().into_int_value(), i64.const_int(1, false), "lr_ni").map_err(llvm_err)?;
        let lr_done_cond = self.builder.build_int_compare(IntPredicate::SGE, lr_next_i, lr_len, "lr_done").map_err(llvm_err)?;
        let lr_next_block = self.builder.get_insert_block().unwrap();
        lr_i.add_incoming(&[(&i64.const_int(0, false), lr_entry), (&lr_next_i, lr_next_block)]);
        lr_list2.add_incoming(&[(&lr_new, lr_entry), (&lr_new2, lr_next_block)]);
        let _ = self.builder.build_conditional_branch(lr_done_cond, lr_done_bb, lr_loop_bb);
        self.builder.position_at_end(lr_done_bb);
        let lr_final = self.builder.build_phi(list_ty, "lr_final").map_err(llvm_err)?;
        lr_final.add_incoming(&[(&lr_new2, lr_next_block)]);
        let _ = self.builder.build_return(Some(&lr_final.as_basic_value()));

        // ---- atomic_list_range(i64, i64) -> {ptr, i64, i64} ----
        let range_fn = self.module.add_function("atomic_list_range", list_ty.fn_type(&[i64.into(), i64.into()], false), None);
        let rg_entry = self.context.append_basic_block(range_fn, "entry");
        self.builder.position_at_end(rg_entry);
        let rg_start = range_fn.get_first_param().unwrap().into_int_value();
        let rg_end = range_fn.get_nth_param(1).unwrap().into_int_value();
        let rg_len = self.builder.build_int_sub(rg_end, rg_start, "rg_len").map_err(llvm_err)?;
        let rg_cap = self.builder.build_int_add(rg_len, i64.const_int(1, false), "rg_cap").map_err(llvm_err)?;
        let rg_list = self.builder.build_call(list_create_fn, &[rg_cap.into()], "rg_list").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("create failed")?;
        let rg_loop_bb = self.context.append_basic_block(range_fn, "rg_loop");
        let rg_done_bb = self.context.append_basic_block(range_fn, "rg_done");
        let rg_check = self.builder.build_int_compare(IntPredicate::SLT, rg_start, rg_end, "rg_check").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(rg_check, rg_loop_bb, rg_done_bb);
        self.builder.position_at_end(rg_loop_bb);
        let rg_i = self.builder.build_phi(i64, "rg_i").map_err(llvm_err)?;
        let rg_list2 = self.builder.build_phi(list_ty, "rg_list2").map_err(llvm_err)?;
        let rg_fat_undef = self.string_type.get_undef();
        let rg_fat_val = self.builder.build_insert_value(rg_fat_undef, rg_i.as_basic_value().into_int_value(), 0, "rg_fat_val").map_err(llvm_err)?;
        let rg_fat = self.builder.build_insert_value(rg_fat_val, self.ptr_ty().const_zero(), 1, "rg_fat").map_err(llvm_err)?;
        let rg_list3 = self.builder.build_call(list_push_fn, &[rg_list2.as_basic_value().into(), rg_fat.as_basic_value_enum().into()], "rg_push").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("push failed")?;
        let rg_next = self.builder.build_int_add(rg_i.as_basic_value().into_int_value(), i64.const_int(1, false), "rg_next").map_err(llvm_err)?;
        let rg_done_cond = self.builder.build_int_compare(IntPredicate::SGE, rg_next, rg_end, "rg_done_cond").map_err(llvm_err)?;
        let rg_next_block = self.builder.get_insert_block().unwrap();
        rg_i.add_incoming(&[(&rg_start, rg_entry), (&rg_next, rg_next_block)]);
        rg_list2.add_incoming(&[(&rg_list, rg_entry), (&rg_list3, rg_next_block)]);
        let _ = self.builder.build_conditional_branch(rg_done_cond, rg_done_bb, rg_loop_bb);
        self.builder.position_at_end(rg_done_bb);
        let rg_final = self.builder.build_phi(list_ty, "rg_final").map_err(llvm_err)?;
        rg_final.add_incoming(&[(&rg_list, rg_entry), (&rg_list3, rg_next_block)]);
        let _ = self.builder.build_return(Some(&rg_final.as_basic_value()));

        // ---- atomic_list_take({ptr, i64, i64}, i64) -> {ptr, i64, i64} ----
        let lt_fn = self.module.add_function("atomic_list_take", list_ty.fn_type(&[list_ty.into(), i64.into()], false), None);
        let lt_entry = self.context.append_basic_block(lt_fn, "entry");
        self.builder.position_at_end(lt_entry);
        let lt_list = lt_fn.get_first_param().unwrap().into_struct_value();
        let lt_n = lt_fn.get_nth_param(1).unwrap().into_int_value();
        let lt_len = self.builder.build_extract_value(lt_list, 1, "lt_len").map_err(llvm_err)?.into_int_value();
        let lt_actual = self.builder.build_select(
            self.builder.build_int_compare(IntPredicate::SLT, lt_n, lt_len, "lt_cmp").map_err(llvm_err)?,
            lt_n, lt_len, "lt_actual").map_err(llvm_err)?.into_int_value();
        let lt_new = self.builder.build_call(list_create_fn, &[lt_actual.into()], "lt_new").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("create failed")?;
        let lt_data = self.builder.build_extract_value(lt_list, 0, "lt_data").map_err(llvm_err)?.into_pointer_value();
        let lt_dp = self.builder.build_pointer_cast(lt_data, self.ptr_ty(), "lt_dp").map_err(llvm_err)?;
        let lt_loop_bb = self.context.append_basic_block(lt_fn, "lt_loop");
        let lt_done_bb = self.context.append_basic_block(lt_fn, "lt_done");
        let _ = self.builder.build_unconditional_branch(lt_loop_bb);
        self.builder.position_at_end(lt_loop_bb);
        let lt_i = self.builder.build_phi(i64, "lt_i").map_err(llvm_err)?;
        let lt_cur = self.builder.build_phi(list_ty, "lt_cur").map_err(llvm_err)?;
        let lt_ep = unsafe { self.builder.build_gep(self.string_type, lt_dp, &[lt_i.as_basic_value().into_int_value()], "lt_ep").map_err(llvm_err) }?;
        let lt_elem = self.builder.build_load(self.string_type, lt_ep, "lt_elem").map_err(llvm_err)?;
        let lt_cur2 = self.builder.build_call(list_push_fn, &[lt_cur.as_basic_value().into(), lt_elem.into()], "lt_push").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("push failed")?;
        let lt_ni = self.builder.build_int_add(lt_i.as_basic_value().into_int_value(), i64.const_int(1, false), "lt_ni").map_err(llvm_err)?;
        let lt_done_cond = self.builder.build_int_compare(IntPredicate::SGE, lt_ni, lt_actual, "lt_done").map_err(llvm_err)?;
        let lt_next_block = self.builder.get_insert_block().unwrap();
        lt_i.add_incoming(&[(&i64.const_int(0, false), lt_entry), (&lt_ni, lt_next_block)]);
        lt_cur.add_incoming(&[(&lt_new, lt_entry), (&lt_cur2, lt_next_block)]);
        let _ = self.builder.build_conditional_branch(lt_done_cond, lt_done_bb, lt_loop_bb);
        self.builder.position_at_end(lt_done_bb);
        let lt_final = self.builder.build_phi(list_ty, "lt_final").map_err(llvm_err)?;
        lt_final.add_incoming(&[(&lt_cur2, lt_next_block)]);
        let _ = self.builder.build_return(Some(&lt_final.as_basic_value()));

        // ---- atomic_list_drop({ptr, i64, i64}, i64) -> {ptr, i64, i64} ----
        let ld_fn = self.module.add_function("atomic_list_drop", list_ty.fn_type(&[list_ty.into(), i64.into()], false), None);
        let ld_entry = self.context.append_basic_block(ld_fn, "entry");
        self.builder.position_at_end(ld_entry);
        let ld_list = ld_fn.get_first_param().unwrap().into_struct_value();
        let ld_n = ld_fn.get_nth_param(1).unwrap().into_int_value();
        let ld_len = self.builder.build_extract_value(ld_list, 1, "ld_len").map_err(llvm_err)?.into_int_value();
        let ld_data = self.builder.build_extract_value(ld_list, 0, "ld_data").map_err(llvm_err)?.into_pointer_value();
        let ld_start = self.builder.build_select(
            self.builder.build_int_compare(IntPredicate::SLT, ld_n, ld_len, "ld_cmp").map_err(llvm_err)?,
            ld_n, ld_len, "ld_start").map_err(llvm_err)?.into_int_value();
        let ld_remaining = self.builder.build_int_sub(ld_len, ld_start, "ld_rem").map_err(llvm_err)?;
        let ld_cap = self.builder.build_int_add(ld_remaining, i64.const_int(1, false), "ld_cap").map_err(llvm_err)?;
        let ld_new = self.builder.build_call(list_create_fn, &[ld_cap.into()], "ld_new").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("create failed")?;
        let ld_dp = self.builder.build_pointer_cast(ld_data, self.ptr_ty(), "ld_dp").map_err(llvm_err)?;
        let ld_loop_bb = self.context.append_basic_block(ld_fn, "ld_loop");
        let ld_done_bb = self.context.append_basic_block(ld_fn, "ld_done");
        let _ = self.builder.build_unconditional_branch(ld_loop_bb);
        self.builder.position_at_end(ld_loop_bb);
        let ld_i = self.builder.build_phi(i64, "ld_i").map_err(llvm_err)?;
        let ld_cur = self.builder.build_phi(list_ty, "ld_cur").map_err(llvm_err)?;
        let ld_idx = self.builder.build_int_add(ld_i.as_basic_value().into_int_value(), ld_start, "ld_idx").map_err(llvm_err)?;
        let ld_ep = unsafe { self.builder.build_gep(self.string_type, ld_dp, &[ld_idx], "ld_ep").map_err(llvm_err) }?;
        let ld_elem = self.builder.build_load(self.string_type, ld_ep, "ld_elem").map_err(llvm_err)?;
        let ld_cur2 = self.builder.build_call(list_push_fn, &[ld_cur.as_basic_value().into(), ld_elem.into()], "ld_push").map_err(llvm_err)?.try_as_basic_value().basic().ok_or("push failed")?;
        let ld_ni = self.builder.build_int_add(ld_i.as_basic_value().into_int_value(), i64.const_int(1, false), "ld_ni").map_err(llvm_err)?;
        let ld_done_cond = self.builder.build_int_compare(IntPredicate::SGE, ld_ni, ld_remaining, "ld_done").map_err(llvm_err)?;
        let ld_next_block = self.builder.get_insert_block().unwrap();
        ld_i.add_incoming(&[(&i64.const_int(0, false), ld_entry), (&ld_ni, ld_next_block)]);
        ld_cur.add_incoming(&[(&ld_new, ld_entry), (&ld_cur2, ld_next_block)]);
        let _ = self.builder.build_conditional_branch(ld_done_cond, ld_done_bb, ld_loop_bb);
        self.builder.position_at_end(ld_done_bb);
        let ld_final = self.builder.build_phi(list_ty, "ld_final").map_err(llvm_err)?;
        ld_final.add_incoming(&[(&ld_cur2, ld_next_block)]);
        let _ = self.builder.build_return(Some(&ld_final.as_basic_value()));

        Ok(())
    }

    pub(super) fn define_list_advanced(&self) -> Result<(), String> {
        let i64 = self.i64_ty();
        let _f64 = self.f64_ty();
        let _ptr = self.ptr_ty();
        let list_ty = self.list_type;
        let str_ty = self.string_type;
        let _b1 = self.bool_ty();
        let i8 = self.context.i8_type();
        let _i32 = self.context.i32_type();

        let _malloc_fn = self.module.get_function("malloc").unwrap();
        let _memcpy_fn = self.module.get_function("memcpy").unwrap();
        let _memcmp_fn = self.module.get_function("memcmp").unwrap();
        // ---- atomic_list_tail({ptr, i64, i64}) -> {ptr, i64, i64} ----
        // Returns a new list without the first element (empty list if input is empty)
        let lt_fn = self.module.add_function("atomic_list_tail", list_ty.fn_type(&[list_ty.into()], false), None);
        let entry = self.context.append_basic_block(lt_fn, "entry");
        self.builder.position_at_end(entry);
        let lt_list = lt_fn.get_first_param().unwrap().into_struct_value();
        let lt_len = self.builder.build_extract_value(lt_list, 1, "len").map_err(llvm_err)?.into_int_value();
        let _lt_empty = self.builder.build_int_compare(IntPredicate::EQ, lt_len, i64.const_int(0, false), "empty").map_err(llvm_err)?;
        let lt_empty_or_one = self.builder.build_int_compare(IntPredicate::SLE, lt_len, i64.const_int(1, false), "empty_or_one").map_err(llvm_err)?;
        let lt_do = self.context.append_basic_block(lt_fn, "do");
        let lt_empty_bb = self.context.append_basic_block(lt_fn, "empty_ret");
        let _ = self.builder.build_conditional_branch(lt_empty_or_one, lt_empty_bb, lt_do);
        self.builder.position_at_end(lt_empty_bb);
        // Return empty list
        let cc0 = self.call_rt("atomic_list_create", &[i64.const_int(0, false).into()])?;
        let lte_r = cc0.try_as_basic_value().basic().unwrap();
        let _ = self.builder.build_return(Some(&lte_r));
        // Copy elements [1..len)
        self.builder.position_at_end(lt_do);
        let lt_nlen = self.builder.build_int_sub(lt_len, i64.const_int(1, false), "nlen").map_err(llvm_err)?;
        let cc = self.call_rt("atomic_list_create", &[lt_nlen.into()])?;
        let lt_new = cc.try_as_basic_value().basic().unwrap().into_struct_value();
        let lt_data = self.builder.build_extract_value(lt_list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        // Loop from i=1 to len
        let lt_new_alloc = self.builder.build_alloca(self.list_type, "newacc").map_err(llvm_err)?;
        self.builder.build_store(lt_new_alloc, lt_new).map_err(llvm_err)?;
        let lt_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(lt_i_alloc, i64.const_int(1, false)).map_err(llvm_err)?;
        let lt_loop = self.context.append_basic_block(lt_fn, "loop");
        let lt_body = self.context.append_basic_block(lt_fn, "body");
        let lt_done = self.context.append_basic_block(lt_fn, "done");
        let _ = self.builder.build_unconditional_branch(lt_loop);
        self.builder.position_at_end(lt_loop);
        let lt_i = self.builder.build_load(i64, lt_i_alloc, "i").map_err(llvm_err)?.into_int_value();
        let lt_cond = self.builder.build_int_compare(IntPredicate::SLT, lt_i, lt_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(lt_cond, lt_body, lt_done);
        self.builder.position_at_end(lt_body);
        let lt_ep = unsafe { self.builder.build_gep(self.string_type, lt_data, &[lt_i], "ep").map_err(llvm_err) }?;
        let lt_fv = self.builder.build_load(self.string_type, lt_ep, "fv").map_err(llvm_err)?;
        let lt_cur = self.builder.build_load(self.list_type, lt_new_alloc, "cur").map_err(llvm_err)?.into_struct_value();
        let cc2 = self.call_rt("atomic_list_push", &[lt_cur.into(), lt_fv.into()])?;
        let lt_nv = cc2.try_as_basic_value().basic().unwrap();
        self.builder.build_store(lt_new_alloc, lt_nv).map_err(llvm_err)?;
        let lt_ni = self.builder.build_int_add(lt_i, i64.const_int(1, false), "ni").map_err(llvm_err)?;
        self.builder.build_store(lt_i_alloc, lt_ni).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(lt_loop);
        self.builder.position_at_end(lt_done);
        let lt_rv = self.builder.build_load(self.list_type, lt_new_alloc, "rv").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&lt_rv));

        // ---- atomic_list_zip({ptr,i64,i64}, {ptr,i64,i64}) -> {ptr,i64,i64} ----
        let lz_fn = self.module.add_function("atomic_list_zip", list_ty.fn_type(&[list_ty.into(), list_ty.into()], false), None);
        let entry = self.context.append_basic_block(lz_fn, "entry");
        self.builder.position_at_end(entry);
        let lz_a = lz_fn.get_first_param().unwrap().into_struct_value();
        let lz_b = lz_fn.get_nth_param(1).unwrap().into_struct_value();
        let lz_alen = self.builder.build_extract_value(lz_a, 1, "alen").map_err(llvm_err)?.into_int_value();
        let lz_blen = self.builder.build_extract_value(lz_b, 1, "blen").map_err(llvm_err)?.into_int_value();
        let lz_altb = self.builder.build_int_compare(IntPredicate::SLT, lz_alen, lz_blen, "altb").map_err(llvm_err)?;
        let lz_min = self.builder.build_select(lz_altb, lz_alen, lz_blen, "min").map_err(llvm_err)?.into_int_value();
        let cc3 = self.call_rt("atomic_list_create", &[lz_min.into()])?;
        let lz_new = cc3.try_as_basic_value().basic().unwrap().into_struct_value();
        let lz_adata = self.builder.build_extract_value(lz_a, 0, "adata").map_err(llvm_err)?.into_pointer_value();
        let lz_bdata = self.builder.build_extract_value(lz_b, 0, "bdata").map_err(llvm_err)?.into_pointer_value();
        let lz_new_alloc = self.builder.build_alloca(self.list_type, "newacc").map_err(llvm_err)?;
        self.builder.build_store(lz_new_alloc, lz_new).map_err(llvm_err)?;
        let lz_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(lz_i_alloc, i64.const_int(0, false)).map_err(llvm_err)?;
        let lz_loop = self.context.append_basic_block(lz_fn, "loop");
        let lz_body = self.context.append_basic_block(lz_fn, "body");
        let lz_done = self.context.append_basic_block(lz_fn, "done");
        let _ = self.builder.build_unconditional_branch(lz_loop);
        self.builder.position_at_end(lz_loop);
        let lz_i = self.builder.build_load(i64, lz_i_alloc, "i").map_err(llvm_err)?.into_int_value();
        let lz_cond = self.builder.build_int_compare(IntPredicate::SLT, lz_i, lz_min, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(lz_cond, lz_body, lz_done);
        self.builder.position_at_end(lz_body);
        let lz_afat = unsafe { self.builder.build_gep(self.string_type, lz_adata, &[lz_i], "afat").map_err(llvm_err) }?;
        let lz_bfat = unsafe { self.builder.build_gep(self.string_type, lz_bdata, &[lz_i], "bfat").map_err(llvm_err) }?;
        let lz_av = self.builder.build_load(self.string_type, lz_afat, "av").map_err(llvm_err)?;
        let lz_bv = self.builder.build_load(self.string_type, lz_bfat, "bv").map_err(llvm_err)?;
        // Allocate tuple struct {fat_a, fat_b}
        let lz_tup_ty = self.context.struct_type(&[self.string_type.into(), self.string_type.into()], false);
        let lz_tup_size = i64.const_int(32, false);
        let lz_tup = self.builder.build_call(self.module.get_function("malloc").unwrap(), &[lz_tup_size.into()], "tup").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_pointer_value();
        let lz_tup_a = self.builder.build_struct_gep(lz_tup_ty, lz_tup, 0, "ta").map_err(llvm_err)?;
        let lz_tup_b = self.builder.build_struct_gep(lz_tup_ty, lz_tup, 1, "tb").map_err(llvm_err)?;
        self.builder.build_store(lz_tup_a, lz_av).map_err(llvm_err)?;
        self.builder.build_store(lz_tup_b, lz_bv).map_err(llvm_err)?;
        // Fat struct: tag=5 (Struct), data=ptr to tuple
        let lz_fat_und = self.string_type.get_undef();
        let lz_fat1 = self.builder.build_insert_value(lz_fat_und, self.i64_ty().const_int(5, false), 0, "tag").map_err(llvm_err)?;
        let lz_fat2 = self.builder.build_insert_value(lz_fat1, lz_tup, 1, "data").map_err(llvm_err)?;
        // Push into result list
        let lz_cur = self.builder.build_load(self.list_type, lz_new_alloc, "cur").map_err(llvm_err)?.into_struct_value();
        let lz_push_cc = self.call_rt("atomic_list_push", &[lz_cur.into(), lz_fat2.as_basic_value_enum().into()])?;
        let lz_nv = lz_push_cc.try_as_basic_value().basic().unwrap();
        self.builder.build_store(lz_new_alloc, lz_nv).map_err(llvm_err)?;
        let lz_ni = self.builder.build_int_add(lz_i, i64.const_int(1, false), "ni").map_err(llvm_err)?;
        self.builder.build_store(lz_i_alloc, lz_ni).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(lz_loop);
        self.builder.position_at_end(lz_done);
        let lz_rv = self.builder.build_load(self.list_type, lz_new_alloc, "rv").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&lz_rv));

        // ---- atomic_list_init({ptr, i64, i64}) -> {ptr, i64, i64} ----
        let li_fn = self.module.add_function("atomic_list_init", list_ty.fn_type(&[list_ty.into()], false), None);
        let entry = self.context.append_basic_block(li_fn, "entry");
        self.builder.position_at_end(entry);
        let li_list = li_fn.get_first_param().unwrap().into_struct_value();
        let li_len = self.builder.build_extract_value(li_list, 1, "len").map_err(llvm_err)?.into_int_value();
        let li_empty = self.builder.build_int_compare(IntPredicate::EQ, li_len, i64.const_int(0, false), "empty").map_err(llvm_err)?;
        let li_do = self.context.append_basic_block(li_fn, "do");
        let li_empty_bb = self.context.append_basic_block(li_fn, "empty_ret");
        let _ = self.builder.build_conditional_branch(li_empty, li_empty_bb, li_do);
        self.builder.position_at_end(li_empty_bb);
        let cce = self.call_rt("atomic_list_create", &[i64.const_int(0, false).into()])?;
        let li_er = cce.try_as_basic_value().basic().unwrap();
        let _ = self.builder.build_return(Some(&li_er));
        self.builder.position_at_end(li_do);
        let li_nlen = self.builder.build_int_sub(li_len, i64.const_int(1, false), "nlen").map_err(llvm_err)?;
        let cc = self.call_rt("atomic_list_create", &[li_nlen.into()])?;
        let li_new_init = cc.try_as_basic_value().basic().unwrap().into_struct_value();
        let li_data = self.builder.build_extract_value(li_list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let li_new_alloc = self.builder.build_alloca(self.list_type, "newacc").map_err(llvm_err)?;
        self.builder.build_store(li_new_alloc, li_new_init).map_err(llvm_err)?;
        let li_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(li_i_alloc, i64.const_int(0, false)).map_err(llvm_err)?;
        let li_loop = self.context.append_basic_block(li_fn, "loop");
        let li_body = self.context.append_basic_block(li_fn, "body");
        let li_done = self.context.append_basic_block(li_fn, "done");
        let _ = self.builder.build_unconditional_branch(li_loop);
        self.builder.position_at_end(li_loop);
        let li_i = self.builder.build_load(i64, li_i_alloc, "i").map_err(llvm_err)?.into_int_value();
        let li_cond = self.builder.build_int_compare(IntPredicate::SLT, li_i, li_nlen, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(li_cond, li_body, li_done);
        self.builder.position_at_end(li_body);
        let li_ep = unsafe { self.builder.build_gep(self.string_type, li_data, &[li_i], "ep").map_err(llvm_err) }?;
        let li_fv = self.builder.build_load(self.string_type, li_ep, "fv").map_err(llvm_err)?;
        let li_cur = self.builder.build_load(self.list_type, li_new_alloc, "cur").map_err(llvm_err)?.into_struct_value();
        let cc2 = self.call_rt("atomic_list_push", &[li_cur.into(), li_fv.into()])?;
        let li_nv = cc2.try_as_basic_value().basic().unwrap();
        self.builder.build_store(li_new_alloc, li_nv).map_err(llvm_err)?;
        let li_ni = self.builder.build_int_add(li_i, i64.const_int(1, false), "ni").map_err(llvm_err)?;
        self.builder.build_store(li_i_alloc, li_ni).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(li_loop);
        self.builder.position_at_end(li_done);
        let li_rv = self.builder.build_load(self.list_type, li_new_alloc, "rv").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&li_rv));

        // ---- atomic_list_last({ptr, i64, i64}) -> {i64, ptr} ----
        let llast_fn = self.module.add_function("atomic_list_last", self.string_type.fn_type(&[list_ty.into()], false), None);
        let entry = self.context.append_basic_block(llast_fn, "entry");
        self.builder.position_at_end(entry);
        let ll_list = llast_fn.get_first_param().unwrap().into_struct_value();
        let ll_len = self.builder.build_extract_value(ll_list, 1, "len").map_err(llvm_err)?.into_int_value();
        let ll_empty = self.builder.build_int_compare(IntPredicate::EQ, ll_len, i64.const_int(0, false), "empty").map_err(llvm_err)?;
        let ll_has = self.context.append_basic_block(llast_fn, "has");
        let ll_none = self.context.append_basic_block(llast_fn, "none");
        let _ = self.builder.build_conditional_branch(ll_empty, ll_none, ll_has);
        self.builder.position_at_end(ll_none);
        let ll_none_val = self.string_type.const_zero();
        let _ = self.builder.build_return(Some(&ll_none_val));
        self.builder.position_at_end(ll_has);
        let ll_data = self.builder.build_extract_value(ll_list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let ll_data_i8 = self.builder.build_pointer_cast(ll_data, self.context.ptr_type(inkwell::AddressSpace::default()), "data_i8").map_err(llvm_err)?;
        let ll_last_idx = self.builder.build_int_sub(ll_len, i64.const_int(1, false), "last_idx").map_err(llvm_err)?;
        let ll_elem_ptr = unsafe { self.builder.build_gep(self.string_type, ll_data_i8, &[ll_last_idx], "elem_ptr").map_err(llvm_err) }?;
        let ll_val = self.builder.build_load(self.string_type, ll_elem_ptr, "val").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&ll_val));

        // ---- atomic_string_chars({i64, ptr}) -> {ptr, i64, i64} ----
        let ch_fn = self.module.add_function("atomic_string_chars",
            list_ty.fn_type(&[str_ty.into()], false), None);
        let entry = self.context.append_basic_block(ch_fn, "entry");
        self.builder.position_at_end(entry);
        let ch_s = ch_fn.get_first_param().unwrap().into_struct_value();
        let ch_len = self.builder.build_extract_value(ch_s, 0, "slen").map_err(llvm_err)?.into_int_value();
        let ch_ptr = self.builder.build_extract_value(ch_s, 1, "sptr").map_err(llvm_err)?.into_pointer_value();
        let cc0 = self.call_rt("atomic_list_create", &[ch_len.into()])?;
        let ch_list_init = cc0.try_as_basic_value().basic().unwrap().into_struct_value();
        let ch_list_alloc = self.builder.build_alloca(self.list_type, "list_acc").map_err(llvm_err)?;
        self.builder.build_store(ch_list_alloc, ch_list_init).map_err(llvm_err)?;
        let ch_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(ch_i_alloc, i64.const_int(0, false)).map_err(llvm_err)?;
        let ch_loop = self.context.append_basic_block(ch_fn, "loop");
        let ch_body = self.context.append_basic_block(ch_fn, "body");
        let ch_done = self.context.append_basic_block(ch_fn, "done");
        let _ = self.builder.build_unconditional_branch(ch_loop);
        self.builder.position_at_end(ch_loop);
        let ch_i = self.builder.build_load(i64, ch_i_alloc, "i").map_err(llvm_err)?.into_int_value();
        let ch_cond = self.builder.build_int_compare(IntPredicate::SLT, ch_i, ch_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(ch_cond, ch_body, ch_done);
        self.builder.position_at_end(ch_body);
        let ch_cp = unsafe { self.builder.build_gep(i8, ch_ptr, &[ch_i], "cp").map_err(llvm_err) }?;
        let ch_c = self.builder.build_load(i8, ch_cp, "c").map_err(llvm_err)?.into_int_value();
        // Create a 1-byte string from this character
        let ch_salloc = self.builder.build_call(self.module.get_function("malloc").unwrap(), &[i64.const_int(1, false).into()], "salloc").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_pointer_value();
        self.builder.build_store(ch_salloc, ch_c).map_err(llvm_err)?;
        let ch_fat = self.string_type.get_undef();
        let ch_fat_tag = self.builder.build_insert_value(ch_fat, self.i64_ty().const_int(1, false), 0, "tag").map_err(llvm_err)?;
        let ch_fat_val = self.builder.build_insert_value(ch_fat_tag, ch_salloc, 1, "data").map_err(llvm_err)?;
        let ch_cur = self.builder.build_load(self.list_type, ch_list_alloc, "cur").map_err(llvm_err)?.into_struct_value();
        let ch_push = self.call_rt("atomic_list_push", &[ch_cur.into(), ch_fat_val.as_basic_value_enum().into()])?;
        let ch_new = ch_push.try_as_basic_value().basic().unwrap();
        self.builder.build_store(ch_list_alloc, ch_new).map_err(llvm_err)?;
        let ch_ni = self.builder.build_int_add(ch_i, i64.const_int(1, false), "ni").map_err(llvm_err)?;
        self.builder.build_store(ch_i_alloc, ch_ni).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(ch_loop);
        self.builder.position_at_end(ch_done);
        let ch_rv = self.builder.build_load(self.list_type, ch_list_alloc, "rv").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&ch_rv));

        // ---- atomic_list_with_index({ptr, i64, i64}) -> {ptr, i64, i64} ----
        let wi_fn = self.module.add_function("atomic_list_with_index", list_ty.fn_type(&[list_ty.into()], false), None);
        let entry = self.context.append_basic_block(wi_fn, "entry");
        self.builder.position_at_end(entry);
        let wi_list = wi_fn.get_first_param().unwrap().into_struct_value();
        let wi_len = self.builder.build_extract_value(wi_list, 1, "len").map_err(llvm_err)?.into_int_value();
        let wi_data = self.builder.build_extract_value(wi_list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let cc = self.call_rt("atomic_list_create", &[wi_len.into()])?;
        let wi_new_init = cc.try_as_basic_value().basic().unwrap().into_struct_value();
        let wi_new_alloc = self.builder.build_alloca(self.list_type, "newacc").map_err(llvm_err)?;
        self.builder.build_store(wi_new_alloc, wi_new_init).map_err(llvm_err)?;
        let wi_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(wi_i_alloc, i64.const_int(0, false)).map_err(llvm_err)?;
        let wi_loop = self.context.append_basic_block(wi_fn, "loop");
        let wi_body = self.context.append_basic_block(wi_fn, "body");
        let wi_done = self.context.append_basic_block(wi_fn, "done");
        let _ = self.builder.build_unconditional_branch(wi_loop);
        self.builder.position_at_end(wi_loop);
        let wi_i = self.builder.build_load(i64, wi_i_alloc, "i").map_err(llvm_err)?.into_int_value();
        let wi_cond = self.builder.build_int_compare(IntPredicate::SLT, wi_i, wi_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(wi_cond, wi_body, wi_done);
        self.builder.position_at_end(wi_body);
        let wi_ep = unsafe { self.builder.build_gep(self.string_type, wi_data, &[wi_i], "ep").map_err(llvm_err) }?;
        let wi_ev = self.builder.build_load(self.string_type, wi_ep, "ev").map_err(llvm_err)?.into_struct_value();
        // Create pair tuple {i64 index, fat_elem}
        let wi_tup_ty = self.context.struct_type(&[i64.into(), self.string_type.into()], false);
        let wi_tup = self.builder.build_call(self.module.get_function("malloc").unwrap(), &[i64.const_int(24, false).into()], "tup").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_pointer_value();
        let wi_tup_i = self.builder.build_struct_gep(wi_tup_ty, wi_tup, 0, "ti").map_err(llvm_err)?;
        let wi_tup_e = self.builder.build_struct_gep(wi_tup_ty, wi_tup, 1, "te").map_err(llvm_err)?;
        self.builder.build_store(wi_tup_i, wi_i).map_err(llvm_err)?;
        self.builder.build_store(wi_tup_e, wi_ev).map_err(llvm_err)?;
        // Wrap in fat struct tag=5 (Struct)
        let wi_fat = self.string_type.get_undef();
        let wi_fat1 = self.builder.build_insert_value(wi_fat, i64.const_int(5, false), 0, "tag").map_err(llvm_err)?;
        let wi_fat2 = self.builder.build_insert_value(wi_fat1, wi_tup, 1, "data").map_err(llvm_err)?;
        let wi_cur = self.builder.build_load(self.list_type, wi_new_alloc, "cur").map_err(llvm_err)?.into_struct_value();
        let cc2 = self.call_rt("atomic_list_push", &[wi_cur.into(), wi_fat2.as_basic_value_enum().into()])?;
        let wi_nv = cc2.try_as_basic_value().basic().unwrap();
        self.builder.build_store(wi_new_alloc, wi_nv).map_err(llvm_err)?;
        let wi_ni = self.builder.build_int_add(wi_i, i64.const_int(1, false), "ni").map_err(llvm_err)?;
        self.builder.build_store(wi_i_alloc, wi_ni).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(wi_loop);
        self.builder.position_at_end(wi_done);
        let wi_rv = self.builder.build_load(self.list_type, wi_new_alloc, "rv").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&wi_rv));

        // ---- atomic_list_unique({ptr, i64, i64}) -> {ptr, i64, i64} ----
        let unq_fn = self.module.add_function("atomic_list_unique", list_ty.fn_type(&[list_ty.into()], false), None);
        let entry = self.context.append_basic_block(unq_fn, "entry");
        self.builder.position_at_end(entry);
        let unq_list = unq_fn.get_first_param().unwrap().into_struct_value();
        let unq_len = self.builder.build_extract_value(unq_list, 1, "len").map_err(llvm_err)?.into_int_value();
        let unq_data = self.builder.build_extract_value(unq_list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let cc3 = self.call_rt("atomic_list_create", &[i64.const_int(0, false).into()])?;
        let unq_new_init = cc3.try_as_basic_value().basic().unwrap().into_struct_value();
        let unq_new_alloc = self.builder.build_alloca(self.list_type, "newacc").map_err(llvm_err)?;
        self.builder.build_store(unq_new_alloc, unq_new_init).map_err(llvm_err)?;
        let unq_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(unq_i_alloc, i64.const_int(0, false)).map_err(llvm_err)?;
        let unq_loop = self.context.append_basic_block(unq_fn, "loop");
        let unq_body = self.context.append_basic_block(unq_fn, "body");
        let unq_done = self.context.append_basic_block(unq_fn, "done");
        let _ = self.builder.build_unconditional_branch(unq_loop);
        self.builder.position_at_end(unq_loop);
        let unq_i = self.builder.build_load(i64, unq_i_alloc, "i").map_err(llvm_err)?.into_int_value();
        let unq_cond = self.builder.build_int_compare(IntPredicate::SLT, unq_i, unq_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(unq_cond, unq_body, unq_done);
        self.builder.position_at_end(unq_body);
        let unq_ep = unsafe { self.builder.build_gep(self.string_type, unq_data, &[unq_i], "ep").map_err(llvm_err) }?;
        let unq_ev = self.builder.build_load(self.string_type, unq_ep, "ev").map_err(llvm_err)?.into_struct_value();
        let unq_cur = self.builder.build_load(self.list_type, unq_new_alloc, "cur").map_err(llvm_err)?.into_struct_value();
        // Check if already in result: call atomic_list_contains
        let cc4 = self.call_rt("atomic_list_contains", &[unq_cur.into(), unq_ev.as_basic_value_enum().into()])?;
        let unq_found = cc4.try_as_basic_value().basic().unwrap().into_int_value();
        let unq_push_bb = self.context.append_basic_block(unq_fn, "push");
        let unq_skip_bb = self.context.append_basic_block(unq_fn, "skip");
        let _ = self.builder.build_conditional_branch(unq_found, unq_skip_bb, unq_push_bb);
        self.builder.position_at_end(unq_push_bb);
        let cc5 = self.call_rt("atomic_list_push", &[unq_cur.into(), unq_ev.as_basic_value_enum().into()])?;
        let unq_nv = cc5.try_as_basic_value().basic().unwrap();
        self.builder.build_store(unq_new_alloc, unq_nv).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(unq_skip_bb);
        self.builder.position_at_end(unq_skip_bb);
        let unq_ni = self.builder.build_int_add(unq_i, i64.const_int(1, false), "ni").map_err(llvm_err)?;
        self.builder.build_store(unq_i_alloc, unq_ni).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(unq_loop);
        self.builder.position_at_end(unq_done);
        let unq_rv = self.builder.build_load(self.list_type, unq_new_alloc, "rv").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&unq_rv));

        // ---- atomic_list_slice({ptr, i64, i64}, i64 start, i64 end) -> {ptr, i64, i64} ----
        let slc_fn = self.module.add_function("atomic_list_slice", list_ty.fn_type(&[list_ty.into(), i64.into(), i64.into()], false), None);
        let entry = self.context.append_basic_block(slc_fn, "entry");
        self.builder.position_at_end(entry);
        let slc_list = slc_fn.get_first_param().unwrap().into_struct_value();
        let slc_start = slc_fn.get_nth_param(1).unwrap().into_int_value();
        let slc_end = slc_fn.get_nth_param(2).unwrap().into_int_value();
        let slc_len = self.builder.build_extract_value(slc_list, 1, "len").map_err(llvm_err)?.into_int_value();
        let slc_data = self.builder.build_extract_value(slc_list, 0, "data").map_err(llvm_err)?.into_pointer_value();
        // Clamp start to [0, len]
        let slc_s_neg = self.builder.build_int_compare(IntPredicate::SLT, slc_start, i64.const_int(0, false), "sneg").map_err(llvm_err)?;
        let slc_s_clamp = self.builder.build_select(slc_s_neg, i64.const_int(0, false), slc_start, "sclamp").map_err(llvm_err)?.into_int_value();
        let slc_s_gt = self.builder.build_int_compare(IntPredicate::SGT, slc_s_clamp, slc_len, "sgt").map_err(llvm_err)?;
        let slc_s_final = self.builder.build_select(slc_s_gt, slc_len, slc_s_clamp, "sfinal").map_err(llvm_err)?.into_int_value();
        // Clamp end
        let slc_e_neg = self.builder.build_int_compare(IntPredicate::SLT, slc_end, i64.const_int(0, false), "eneg").map_err(llvm_err)?;
        let slc_e_clamp = self.builder.build_select(slc_e_neg, i64.const_int(0, false), slc_end, "eclamp").map_err(llvm_err)?.into_int_value();
        let slc_e_gt = self.builder.build_int_compare(IntPredicate::SGT, slc_e_clamp, slc_len, "egt").map_err(llvm_err)?;
        let slc_e_final = self.builder.build_select(slc_e_gt, slc_len, slc_e_clamp, "efinal").map_err(llvm_err)?.into_int_value();
        // Compute result length
        let slc_rlen = self.builder.build_int_sub(slc_e_final, slc_s_final, "rlen").map_err(llvm_err)?;
        let slc_rlen_neg = self.builder.build_int_compare(IntPredicate::SLT, slc_rlen, i64.const_int(0, false), "rneg").map_err(llvm_err)?;
        let slc_rlen_final = self.builder.build_select(slc_rlen_neg, i64.const_int(0, false), slc_rlen, "rlenf").map_err(llvm_err)?.into_int_value();
        let cc6 = self.call_rt("atomic_list_create", &[slc_rlen_final.into()])?;
        let slc_new_init = cc6.try_as_basic_value().basic().unwrap().into_struct_value();
        let slc_new_alloc = self.builder.build_alloca(self.list_type, "newacc").map_err(llvm_err)?;
        self.builder.build_store(slc_new_alloc, slc_new_init).map_err(llvm_err)?;
        let slc_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(slc_i_alloc, slc_s_final).map_err(llvm_err)?;
        let slc_loop = self.context.append_basic_block(slc_fn, "loop");
        let slc_body = self.context.append_basic_block(slc_fn, "body");
        let slc_done = self.context.append_basic_block(slc_fn, "done");
        let _ = self.builder.build_unconditional_branch(slc_loop);
        self.builder.position_at_end(slc_loop);
        let slc_i = self.builder.build_load(i64, slc_i_alloc, "i").map_err(llvm_err)?.into_int_value();
        let slc_cond = self.builder.build_int_compare(IntPredicate::SLT, slc_i, slc_e_final, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(slc_cond, slc_body, slc_done);
        self.builder.position_at_end(slc_body);
        let slc_ep = unsafe { self.builder.build_gep(self.string_type, slc_data, &[slc_i], "ep").map_err(llvm_err) }?;
        let slc_ev = self.builder.build_load(self.string_type, slc_ep, "ev").map_err(llvm_err)?;
        let slc_cur = self.builder.build_load(self.list_type, slc_new_alloc, "cur").map_err(llvm_err)?.into_struct_value();
        let cc7 = self.call_rt("atomic_list_push", &[slc_cur.into(), slc_ev.into()])?;
        let slc_nv = cc7.try_as_basic_value().basic().unwrap();
        self.builder.build_store(slc_new_alloc, slc_nv).map_err(llvm_err)?;
        let slc_ni = self.builder.build_int_add(slc_i, i64.const_int(1, false), "ni").map_err(llvm_err)?;
        self.builder.build_store(slc_i_alloc, slc_ni).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(slc_loop);
        self.builder.position_at_end(slc_done);
        let slc_rv = self.builder.build_load(self.list_type, slc_new_alloc, "rv").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&slc_rv));

        // ---- atomic_string_split_lines({i64, ptr}) -> {ptr, i64, i64} ----
        let sl_fn = self.module.add_function("atomic_string_split_lines",
            list_ty.fn_type(&[str_ty.into()], false), None);
        let entry = self.context.append_basic_block(sl_fn, "entry");
        self.builder.position_at_end(entry);
        let sl_s = sl_fn.get_first_param().unwrap().into_struct_value();
        let sl_len = self.builder.build_extract_value(sl_s, 0, "slen").map_err(llvm_err)?.into_int_value();
        let sl_ptr = self.builder.build_extract_value(sl_s, 1, "sptr").map_err(llvm_err)?.into_pointer_value();
        let cc4 = self.call_rt("atomic_list_create", &[i64.const_int(0, false).into()])?;
        let sl_list_init = cc4.try_as_basic_value().basic().unwrap().into_struct_value();
        // Use alloca to accumulate list across loop iterations
        let sl_list_alloc = self.builder.build_alloca(self.list_type, "list_acc").map_err(llvm_err)?;
        self.builder.build_store(sl_list_alloc, sl_list_init).map_err(llvm_err)?;
        // Scan through string, splitting on '\n'
        let sl_start_alloc = self.builder.build_alloca(i64, "start").map_err(llvm_err)?;
        let sl_i_alloc = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(sl_start_alloc, i64.const_int(0, false)).map_err(llvm_err)?;
        self.builder.build_store(sl_i_alloc, i64.const_int(0, false)).map_err(llvm_err)?;
        let sl_loop = self.context.append_basic_block(sl_fn, "loop");
        let sl_body_bb = self.context.append_basic_block(sl_fn, "body");
        let sl_done = self.context.append_basic_block(sl_fn, "done");
        let _ = self.builder.build_unconditional_branch(sl_loop);
        self.builder.position_at_end(sl_loop);
        let sl_i = self.builder.build_load(i64, sl_i_alloc, "sl_i").map_err(llvm_err)?.into_int_value();
        let sl_cond = self.builder.build_int_compare(IntPredicate::SLE, sl_i, sl_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(sl_cond, sl_body_bb, sl_done);
        self.builder.position_at_end(sl_body_bb);
        // Check if at end or char is '\n'
        let sl_at_end = self.builder.build_int_compare(IntPredicate::EQ, sl_i, sl_len, "atend").map_err(llvm_err)?;
        let sl_cp = unsafe { self.builder.build_gep(i8, sl_ptr, &[sl_i], "cp").map_err(llvm_err) }?;
        let sl_c = self.builder.build_load(i8, sl_cp, "c").map_err(llvm_err)?.into_int_value();
        let sl_is_nl = self.builder.build_int_compare(IntPredicate::EQ, sl_c, i8.const_int(b'\n' as u64, false), "isnl").map_err(llvm_err)?;
        let sl_cr = self.builder.build_int_compare(IntPredicate::EQ, sl_c, i8.const_int(b'\r' as u64, false), "iscr").map_err(llvm_err)?;
        let sl_split = self.builder.build_or(sl_at_end, self.builder.build_or(sl_is_nl, sl_cr, "").map_err(llvm_err)?, "split").map_err(llvm_err)?;
        let sl_cont = self.context.append_basic_block(sl_fn, "cont");
        let sl_extract = self.context.append_basic_block(sl_fn, "extract");
        let _ = self.builder.build_conditional_branch(sl_split, sl_extract, sl_cont);
        // Extract line from start to i
        self.builder.position_at_end(sl_extract);
        let sl_start = self.builder.build_load(i64, sl_start_alloc, "slstart").map_err(llvm_err)?.into_int_value();
        let sl_seg_len = self.builder.build_int_sub(sl_i, sl_start, "seg_len").map_err(llvm_err)?;
        let sl_seg_data = unsafe { self.builder.build_gep(i8, sl_ptr, &[sl_start], "segp").map_err(llvm_err) }?;
        // Skip \r if next char is \n
        let sl_next_i = self.builder.build_int_add(sl_i, i64.const_int(1, false), "nexti").map_err(llvm_err)?;
        // Create string for this segment: malloc + memcpy
        let sl_salloc = self.builder.build_call(self.module.get_function("malloc").unwrap(), &[sl_seg_len.into()], "seg").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_pointer_value();
        let _ = self.builder.build_call(self.module.get_function("memcpy").unwrap(), &[sl_salloc.into(), sl_seg_data.into(), sl_seg_len.into()], "").map_err(llvm_err)?;
        let sl_fat = self.string_type.get_undef();
        let sl_fat_tag = self.builder.build_insert_value(sl_fat, self.i64_ty().const_int(1, false), 0, "tag").map_err(llvm_err)?;
        let sl_fat_val = self.builder.build_insert_value(sl_fat_tag, sl_salloc, 1, "data").map_err(llvm_err)?;
        let sl_cur_list = self.builder.build_load(self.list_type, sl_list_alloc, "cur_list").map_err(llvm_err)?.into_struct_value();
        let sl_push_cc = self.call_rt("atomic_list_push", &[sl_cur_list.into(), sl_fat_val.as_basic_value_enum().into()])?;
        let sl_new_list = sl_push_cc.try_as_basic_value().basic().unwrap();
        self.builder.build_store(sl_list_alloc, sl_new_list).map_err(llvm_err)?;
        self.builder.build_store(sl_start_alloc, sl_next_i).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(sl_cont);
        // Continue scanning
        self.builder.position_at_end(sl_cont);
        let sl_i2 = self.builder.build_load(i64, sl_i_alloc, "i2").map_err(llvm_err)?.into_int_value();
        let sl_i_next = self.builder.build_int_add(sl_i2, i64.const_int(1, false), "inext").map_err(llvm_err)?;
        self.builder.build_store(sl_i_alloc, sl_i_next).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(sl_loop);
        self.builder.position_at_end(sl_done);
        let sl_result = self.builder.build_load(self.list_type, sl_list_alloc, "result").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&sl_result));

        // ---- atomic_string_index_of({i64, ptr}, {i64, ptr}) -> i64 (returns -1 if not found) ----
        let sio_fn = self.module.add_function("atomic_string_index_of",
            i64.fn_type(&[str_ty.into(), str_ty.into()], false), None);
        let entry = self.context.append_basic_block(sio_fn, "entry");
        self.builder.position_at_end(entry);
        let sio_hay = sio_fn.get_first_param().unwrap().into_struct_value();
        let sio_nee = sio_fn.get_nth_param(1).unwrap().into_struct_value();
        let sio_hlen = self.builder.build_extract_value(sio_hay, 0, "hlen").map_err(llvm_err)?.into_int_value();
        let sio_hptr = self.builder.build_extract_value(sio_hay, 1, "hptr").map_err(llvm_err)?.into_pointer_value();
        let sio_nlen = self.builder.build_extract_value(sio_nee, 0, "nlen").map_err(llvm_err)?.into_int_value();
        let sio_nptr = self.builder.build_extract_value(sio_nee, 1, "nptr").map_err(llvm_err)?.into_pointer_value();
        // If needle empty, return 0
        let sio_nempty = self.builder.build_int_compare(IntPredicate::EQ, sio_nlen, i64.const_int(0, false), "nempty").map_err(llvm_err)?;
        let sio_nok = self.builder.build_int_compare(IntPredicate::SLE, sio_nlen, sio_hlen, "nok").map_err(llvm_err)?;
        let _sio_can = self.builder.build_and(sio_nok, self.builder.build_not(sio_nempty, "").map_err(llvm_err)?, "").map_err(llvm_err)?;
        let sio_max = self.builder.build_int_sub(sio_hlen, sio_nlen, "max").map_err(llvm_err)?;
        // Outer loop
        let sio_i = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(sio_i, i64.const_int(0, false)).map_err(llvm_err)?;
        let sio_oloop = self.context.append_basic_block(sio_fn, "oloop");
        let sio_obody = self.context.append_basic_block(sio_fn, "obody");
        let sio_notfound = self.context.append_basic_block(sio_fn, "notfound");
        let _ = self.builder.build_unconditional_branch(sio_oloop);
        self.builder.position_at_end(sio_oloop);
        let sio_iv = self.builder.build_load(i64, sio_i, "iv").map_err(llvm_err)?.into_int_value();
        let sio_cond = self.builder.build_int_compare(IntPredicate::SLE, sio_iv, sio_max, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(sio_cond, sio_obody, sio_notfound);
        self.builder.position_at_end(sio_obody);
        let sio_hp = unsafe { self.builder.build_gep(i8, sio_hptr, &[sio_iv], "hp").map_err(llvm_err) }?;
        let sio_eq = self.builder.build_call(self.module.get_function("memcmp").unwrap(), &[sio_hp.into(), sio_nptr.into(), sio_nlen.into()], "eq").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_int_value();
        let sio_match = self.builder.build_int_compare(IntPredicate::EQ, sio_eq, self.i32_ty().const_int(0, false), "match").map_err(llvm_err)?;
        let sio_match_bb = self.context.append_basic_block(sio_fn, "match");
        let sio_next_bb = self.context.append_basic_block(sio_fn, "next");
        let _ = self.builder.build_conditional_branch(sio_match, sio_match_bb, sio_next_bb);
        self.builder.position_at_end(sio_match_bb);
        let _ = self.builder.build_return(Some(&sio_iv));
        self.builder.position_at_end(sio_next_bb);
        let sio_next_i = self.builder.build_int_add(sio_iv, i64.const_int(1, false), "nexti").map_err(llvm_err)?;
        self.builder.build_store(sio_i, sio_next_i).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(sio_oloop);
        self.builder.position_at_end(sio_notfound);
        let _ = self.builder.build_return(Some(&i64.const_int(-1i64 as u64, true)));

        // ---- atomic_list_flatten({ptr, i64, i64}) -> {ptr, i64, i64} ----
        let fl_fn = self.module.add_function("atomic_list_flatten", list_ty.fn_type(&[list_ty.into()], false), None);
        let fl_entry = self.context.append_basic_block(fl_fn, "entry");
        self.builder.position_at_end(fl_entry);
        let fl_input = fl_fn.get_first_param().unwrap().into_struct_value();
        let fl_data = self.builder.build_extract_value(fl_input, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let fl_len = self.builder.build_extract_value(fl_input, 1, "len").map_err(llvm_err)?.into_int_value();
        let fl_result = self.call_rt("atomic_list_create", &[i64.const_int(4, false).into()])?;
        let fl_rb = fl_result.try_as_basic_value().basic().unwrap();
        let fl_ra = self.builder.build_alloca(self.list_type, "fl_res").map_err(llvm_err)?;
        self.builder.build_store(fl_ra, fl_rb).map_err(llvm_err)?;
        let fl_oi = self.builder.build_alloca(i64, "fl_oi").map_err(llvm_err)?;
        self.builder.build_store(fl_oi, i64.const_int(0, false)).map_err(llvm_err)?;
        let fl_oloop = self.context.append_basic_block(fl_fn, "oloop");
        let fl_obody = self.context.append_basic_block(fl_fn, "obody");
        let fl_odone = self.context.append_basic_block(fl_fn, "odone");
        let _ = self.builder.build_unconditional_branch(fl_oloop);
        self.builder.position_at_end(fl_oloop);
        let fl_oi_val = self.builder.build_load(i64, fl_oi, "oi").map_err(llvm_err)?.into_int_value();
        let fl_ocond = self.builder.build_int_compare(IntPredicate::SLT, fl_oi_val, fl_len, "ocond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(fl_ocond, fl_obody, fl_odone);
        self.builder.position_at_end(fl_obody);
        let fl_elem_ptr = unsafe { self.builder.build_gep(self.string_type, fl_data, &[fl_oi_val], "ep").map_err(llvm_err) }?;
        let fl_elem = self.builder.build_load(self.string_type, fl_elem_ptr, "elem").map_err(llvm_err)?.into_struct_value();
        let fl_elem_tag = self.builder.build_extract_value(fl_elem, 0, "etag").map_err(llvm_err)?.into_int_value();
        let fl_is_list = self.builder.build_int_compare(IntPredicate::EQ, fl_elem_tag, i64.const_int(6, false), "islist").map_err(llvm_err)?;
        let fl_push_flat = self.context.append_basic_block(fl_fn, "push_flat");
        let fl_push_direct = self.context.append_basic_block(fl_fn, "push_direct");
        let fl_push_next = self.context.append_basic_block(fl_fn, "push_next");
        let _ = self.builder.build_conditional_branch(fl_is_list, fl_push_flat, fl_push_direct);
        self.builder.position_at_end(fl_push_flat);
        let fl_edata = self.builder.build_extract_value(fl_elem, 1, "edata").map_err(llvm_err)?.into_pointer_value();
        let fl_inner = self.builder.build_load(self.list_type, fl_edata, "inner").map_err(llvm_err)?.into_struct_value();
        let fl_idata = self.builder.build_extract_value(fl_inner, 0, "idata").map_err(llvm_err)?.into_pointer_value();
        let fl_ilen = self.builder.build_extract_value(fl_inner, 1, "ilen").map_err(llvm_err)?.into_int_value();
        let fl_ii = self.builder.build_alloca(i64, "fl_ii").map_err(llvm_err)?;
        self.builder.build_store(fl_ii, i64.const_int(0, false)).map_err(llvm_err)?;
        let fl_iloop = self.context.append_basic_block(fl_fn, "iloop");
        let fl_ibody = self.context.append_basic_block(fl_fn, "ibody");
        let fl_idone = self.context.append_basic_block(fl_fn, "idone");
        let _ = self.builder.build_unconditional_branch(fl_iloop);
        self.builder.position_at_end(fl_iloop);
        let fl_ii_val = self.builder.build_load(i64, fl_ii, "ii").map_err(llvm_err)?.into_int_value();
        let fl_icond = self.builder.build_int_compare(IntPredicate::SLT, fl_ii_val, fl_ilen, "icond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(fl_icond, fl_ibody, fl_idone);
        self.builder.position_at_end(fl_ibody);
        let fl_ie_ptr = unsafe { self.builder.build_gep(self.string_type, fl_idata, &[fl_ii_val], "iep").map_err(llvm_err) }?;
        let fl_ie = self.builder.build_load(self.string_type, fl_ie_ptr, "ie").map_err(llvm_err)?.into_struct_value();
        let fl_cl = self.builder.build_load(self.list_type, fl_ra, "cl").map_err(llvm_err)?.into_struct_value();
        let fl_ps = self.call_rt("atomic_list_push", &[fl_cl.into(), fl_ie.as_basic_value_enum().into()])?;
        self.builder.build_store(fl_ra, fl_ps.try_as_basic_value().basic().unwrap()).map_err(llvm_err)?;
        let fl_ii_inc = self.builder.build_int_add(fl_ii_val, i64.const_int(1, false), "iiinc").map_err(llvm_err)?;
        self.builder.build_store(fl_ii, fl_ii_inc).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(fl_iloop);
        self.builder.position_at_end(fl_idone);
        let _ = self.builder.build_unconditional_branch(fl_push_next);
        self.builder.position_at_end(fl_push_direct);
        let fl_cl2 = self.builder.build_load(self.list_type, fl_ra, "cl2").map_err(llvm_err)?.into_struct_value();
        let fl_ps2 = self.call_rt("atomic_list_push", &[fl_cl2.into(), fl_elem.as_basic_value_enum().into()])?;
        self.builder.build_store(fl_ra, fl_ps2.try_as_basic_value().basic().unwrap()).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(fl_push_next);
        self.builder.position_at_end(fl_push_next);
        let fl_oi_inc = self.builder.build_int_add(fl_oi_val, i64.const_int(1, false), "oiinc").map_err(llvm_err)?;
        self.builder.build_store(fl_oi, fl_oi_inc).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(fl_oloop);
        self.builder.position_at_end(fl_odone);
        let fl_res = self.builder.build_load(self.list_type, fl_ra, "fl_res").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&fl_res));

        // ---- atomic_list_split_at({ptr, i64, i64}, i64) -> {ptr, i64, i64} ----
        let sa_fn = self.module.add_function("atomic_list_split_at", list_ty.fn_type(&[list_ty.into(), i64.into()], false), None);
        let sa_entry = self.context.append_basic_block(sa_fn, "entry");
        self.builder.position_at_end(sa_entry);
        let sa_in = sa_fn.get_first_param().unwrap().into_struct_value();
        let sa_idx = sa_fn.get_nth_param(1).unwrap().into_int_value();
        let sa_data = self.builder.build_extract_value(sa_in, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let sa_len = self.builder.build_extract_value(sa_in, 1, "len").map_err(llvm_err)?.into_int_value();
        let sa_clamped = self.builder.build_int_compare(IntPredicate::SLT, sa_idx, i64.const_int(0, false), "cl").map_err(llvm_err)?;
        let sa_idx0 = self.builder.build_select(sa_clamped, i64.const_int(0, false), sa_idx, "idx0").map_err(llvm_err)?.into_int_value();
        let sa_cl2 = self.builder.build_int_compare(IntPredicate::SGT, sa_idx0, sa_len, "cl2").map_err(llvm_err)?;
        let sa_idx_safe = self.builder.build_select(sa_cl2, sa_len, sa_idx0, "idx_safe").map_err(llvm_err)?.into_int_value();
        let sa_r1 = self.call_rt("atomic_list_create", &[i64.const_int(4, false).into()])?;
        let sa_r1v = sa_r1.try_as_basic_value().basic().unwrap();
        let sa_a1 = self.builder.build_alloca(self.list_type, "sa_a1").map_err(llvm_err)?;
        self.builder.build_store(sa_a1, sa_r1v).map_err(llvm_err)?;
        let sa_r2 = self.call_rt("atomic_list_create", &[i64.const_int(4, false).into()])?;
        let sa_r2v = sa_r2.try_as_basic_value().basic().unwrap();
        let sa_a2 = self.builder.build_alloca(self.list_type, "sa_a2").map_err(llvm_err)?;
        self.builder.build_store(sa_a2, sa_r2v).map_err(llvm_err)?;
        let sa_i = self.builder.build_alloca(i64, "sa_i").map_err(llvm_err)?;
        self.builder.build_store(sa_i, i64.const_int(0, false)).map_err(llvm_err)?;
        let sa_loop = self.context.append_basic_block(sa_fn, "loop");
        let sa_body = self.context.append_basic_block(sa_fn, "body");
        let sa_done = self.context.append_basic_block(sa_fn, "done");
        let _ = self.builder.build_unconditional_branch(sa_loop);
        self.builder.position_at_end(sa_loop);
        let sa_iv = self.builder.build_load(i64, sa_i, "iv").map_err(llvm_err)?.into_int_value();
        let sa_cond = self.builder.build_int_compare(IntPredicate::SLT, sa_iv, sa_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(sa_cond, sa_body, sa_done);
        self.builder.position_at_end(sa_body);
        let sa_ep = unsafe { self.builder.build_gep(self.string_type, sa_data, &[sa_iv], "ep").map_err(llvm_err) }?;
        let sa_ev = self.builder.build_load(self.string_type, sa_ep, "ev").map_err(llvm_err)?.into_struct_value();
        let sa_before = self.builder.build_int_compare(IntPredicate::SLT, sa_iv, sa_idx_safe, "before").map_err(llvm_err)?;
        let sa_l1 = self.builder.build_load(self.list_type, sa_a1, "l1").map_err(llvm_err)?.into_struct_value();
        let sa_l2 = self.builder.build_load(self.list_type, sa_a2, "l2").map_err(llvm_err)?.into_struct_value();
        let sa_ps1 = self.call_rt("atomic_list_push", &[sa_l1.into(), sa_ev.as_basic_value_enum().into()])?;
        let sa_ps2 = self.call_rt("atomic_list_push", &[sa_l2.into(), sa_ev.as_basic_value_enum().into()])?;
        let sa_l1_sel = self.builder.build_select(sa_before, sa_ps1.try_as_basic_value().basic().unwrap(), sa_l1.into(), "l1s").map_err(llvm_err)?;
        let sa_l2_sel = self.builder.build_select(sa_before, sa_l2.into(), sa_ps2.try_as_basic_value().basic().unwrap(), "l2s").map_err(llvm_err)?;
        self.builder.build_store(sa_a1, sa_l1_sel).map_err(llvm_err)?;
        self.builder.build_store(sa_a2, sa_l2_sel).map_err(llvm_err)?;
        let sa_inc = self.builder.build_int_add(sa_iv, i64.const_int(1, false), "inc").map_err(llvm_err)?;
        self.builder.build_store(sa_i, sa_inc).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(sa_loop);
        self.builder.position_at_end(sa_done);
        // Return as list of 2 lists
        let sa_malloc = self.builder.build_call(self.module.get_function("malloc").unwrap(), &[i64.const_int(16, false).into()], "sa_m").map_err(llvm_err)?.try_as_basic_value().basic().unwrap().into_pointer_value();
        let sa_l1f = self.builder.build_load(self.list_type, sa_a1, "l1f").map_err(llvm_err)?.into_struct_value();
        let sa_fat1 = self.string_type.get_undef();
        let sa_fat1t = self.builder.build_insert_value(sa_fat1, i64.const_int(6, false), 0, "t1").map_err(llvm_err)?;
        let sa_l1p = self.builder.build_alloca(self.list_type, "l1p").map_err(llvm_err)?;
        self.builder.build_store(sa_l1p, sa_l1f).map_err(llvm_err)?;
        let sa_fat1v = self.builder.build_insert_value(sa_fat1t, sa_l1p, 1, "v1").map_err(llvm_err)?;
        self.builder.build_store(sa_malloc, sa_fat1v).map_err(llvm_err)?;
        let sa_slot2 = unsafe { self.builder.build_gep(self.string_type, sa_malloc, &[i64.const_int(1, false)], "s2").map_err(llvm_err) }?;
        let sa_l2f = self.builder.build_load(self.list_type, sa_a2, "l2f").map_err(llvm_err)?.into_struct_value();
        let sa_fat2 = self.string_type.get_undef();
        let sa_fat2t = self.builder.build_insert_value(sa_fat2, i64.const_int(6, false), 0, "t2").map_err(llvm_err)?;
        let sa_l2p = self.builder.build_alloca(self.list_type, "l2p").map_err(llvm_err)?;
        self.builder.build_store(sa_l2p, sa_l2f).map_err(llvm_err)?;
        let sa_fat2v = self.builder.build_insert_value(sa_fat2t, sa_l2p, 1, "v2").map_err(llvm_err)?;
        self.builder.build_store(sa_slot2, sa_fat2v).map_err(llvm_err)?;
        let sa_rt = self.list_type.get_undef();
        let sa_rtd = self.builder.build_insert_value(sa_rt, sa_malloc, 0, "d").map_err(llvm_err)?;
        let sa_rtl = self.builder.build_insert_value(sa_rtd, i64.const_int(2, false), 1, "l").map_err(llvm_err)?;
        let sa_rtc = self.builder.build_insert_value(sa_rtl, i64.const_int(2, false), 2, "c").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&sa_rtc));

        // ---- atomic_list_chunks({ptr, i64, i64}, i64 chunk_size) -> {ptr, i64, i64} ----
        let ch_fn = self.module.add_function("atomic_list_chunks", list_ty.fn_type(&[list_ty.into(), i64.into()], false), None);
        let ch_entry = self.context.append_basic_block(ch_fn, "entry");
        self.builder.position_at_end(ch_entry);
        let ch_in = ch_fn.get_first_param().unwrap().into_struct_value();
        let ch_csize = ch_fn.get_nth_param(1).unwrap().into_int_value();
        let ch_data = self.builder.build_extract_value(ch_in, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let ch_len = self.builder.build_extract_value(ch_in, 1, "len").map_err(llvm_err)?.into_int_value();
        let ch_cz = self.builder.build_int_compare(IntPredicate::SLT, ch_csize, i64.const_int(1, false), "cz").map_err(llvm_err)?;
        let ch_csafe = self.builder.build_select(ch_cz, i64.const_int(1, false), ch_csize, "csafe").map_err(llvm_err)?.into_int_value();
        let ch_res = self.call_rt("atomic_list_create", &[i64.const_int(4, false).into()])?;
        let ch_resv = ch_res.try_as_basic_value().basic().unwrap();
        let ch_ra = self.builder.build_alloca(self.list_type, "ch_ra").map_err(llvm_err)?;
        self.builder.build_store(ch_ra, ch_resv).map_err(llvm_err)?;
        let ch_i = self.builder.build_alloca(i64, "ch_i").map_err(llvm_err)?;
        self.builder.build_store(ch_i, i64.const_int(0, false)).map_err(llvm_err)?;
        let ch_loop = self.context.append_basic_block(ch_fn, "loop");
        let ch_body = self.context.append_basic_block(ch_fn, "body");
        let ch_done = self.context.append_basic_block(ch_fn, "done");
        let _ = self.builder.build_unconditional_branch(ch_loop);
        self.builder.position_at_end(ch_loop);
        let ch_iv = self.builder.build_load(i64, ch_i, "iv").map_err(llvm_err)?.into_int_value();
        let ch_cond = self.builder.build_int_compare(IntPredicate::SLT, ch_iv, ch_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(ch_cond, ch_body, ch_done);
        self.builder.position_at_end(ch_body);
        let ch_subl = self.call_rt("atomic_list_create", &[ch_csafe.into()])?;
        let ch_sublv = ch_subl.try_as_basic_value().basic().unwrap();
        let ch_sa = self.builder.build_alloca(self.list_type, "ch_sa").map_err(llvm_err)?;
        self.builder.build_store(ch_sa, ch_sublv).map_err(llvm_err)?;
        let ch_j = self.builder.build_alloca(i64, "ch_j").map_err(llvm_err)?;
        self.builder.build_store(ch_j, i64.const_int(0, false)).map_err(llvm_err)?;
        let ch_iloop = self.context.append_basic_block(ch_fn, "iloop");
        let ch_ibody = self.context.append_basic_block(ch_fn, "ibody");
        let ch_idone = self.context.append_basic_block(ch_fn, "idone");
        let _ = self.builder.build_unconditional_branch(ch_iloop);
        self.builder.position_at_end(ch_iloop);
        let ch_jv = self.builder.build_load(i64, ch_j, "jv").map_err(llvm_err)?.into_int_value();
        let ch_jc = self.builder.build_int_compare(IntPredicate::SLT, ch_jv, ch_csafe, "jc").map_err(llvm_err)?;
        let ch_end = self.builder.build_int_compare(IntPredicate::SGE, ch_iv, ch_len, "end").map_err(llvm_err)?;
        let ch_ic = self.builder.build_and(ch_jc, self.builder.build_not(ch_end, "").map_err(llvm_err)?, "ic").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(ch_ic, ch_ibody, ch_idone);
        self.builder.position_at_end(ch_ibody);
        let ch_cur_i = self.builder.build_load(i64, ch_i, "cur_i").map_err(llvm_err)?.into_int_value();
        let ch_ep = unsafe { self.builder.build_gep(self.string_type, ch_data, &[ch_cur_i], "ep").map_err(llvm_err) }?;
        let ch_ev = self.builder.build_load(self.string_type, ch_ep, "ev").map_err(llvm_err)?.into_struct_value();
        let ch_cl = self.builder.build_load(self.list_type, ch_sa, "cl").map_err(llvm_err)?.into_struct_value();
        let ch_ps = self.call_rt("atomic_list_push", &[ch_cl.into(), ch_ev.as_basic_value_enum().into()])?;
        self.builder.build_store(ch_sa, ch_ps.try_as_basic_value().basic().unwrap()).map_err(llvm_err)?;
        let ch_ivi = self.builder.build_int_add(ch_cur_i, i64.const_int(1, false), "ivi").map_err(llvm_err)?;
        self.builder.build_store(ch_i, ch_ivi).map_err(llvm_err)?;
        let ch_jvi = self.builder.build_int_add(ch_jv, i64.const_int(1, false), "jvi").map_err(llvm_err)?;
        self.builder.build_store(ch_j, ch_jvi).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(ch_iloop);
        self.builder.position_at_end(ch_idone);
        let ch_subl_fat = self.string_type.get_undef();
        let ch_sublft = self.builder.build_insert_value(ch_subl_fat, i64.const_int(6, false), 0, "st").map_err(llvm_err)?;
        let ch_subl_l = self.builder.build_load(self.list_type, ch_sa, "sl").map_err(llvm_err)?.into_struct_value();
        let ch_sp = self.builder.build_alloca(self.list_type, "ch_sp").map_err(llvm_err)?;
        self.builder.build_store(ch_sp, ch_subl_l).map_err(llvm_err)?;
        let ch_sublfv = self.builder.build_insert_value(ch_sublft, ch_sp, 1, "sv").map_err(llvm_err)?;
        let ch_rl = self.builder.build_load(self.list_type, ch_ra, "rl").map_err(llvm_err)?.into_struct_value();
        let ch_rps = self.call_rt("atomic_list_push", &[ch_rl.into(), ch_sublfv.as_basic_value_enum().into()])?;
        self.builder.build_store(ch_ra, ch_rps.try_as_basic_value().basic().unwrap()).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(ch_loop);
        self.builder.position_at_end(ch_done);
        let ch_rt = self.builder.build_load(self.list_type, ch_ra, "ch_rt").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&ch_rt));

        // ---- atomic_list_windows({ptr, i64, i64}, i64 win_size) -> {ptr, i64, i64} ----
        let wn_fn = self.module.add_function("atomic_list_windows", list_ty.fn_type(&[list_ty.into(), i64.into()], false), None);
        let wn_entry = self.context.append_basic_block(wn_fn, "entry");
        self.builder.position_at_end(wn_entry);
        let wn_in = wn_fn.get_first_param().unwrap().into_struct_value();
        let wn_wsize = wn_fn.get_nth_param(1).unwrap().into_int_value();
        let wn_data = self.builder.build_extract_value(wn_in, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let wn_len = self.builder.build_extract_value(wn_in, 1, "len").map_err(llvm_err)?.into_int_value();
        let wn_wz = self.builder.build_int_compare(IntPredicate::SLT, wn_wsize, i64.const_int(1, false), "wz").map_err(llvm_err)?;
        let wn_wsafe = self.builder.build_select(wn_wz, i64.const_int(1, false), wn_wsize, "wsafe").map_err(llvm_err)?.into_int_value();
        let wn_tmp = self.builder.build_int_sub(wn_len, wn_wsafe, "tmp").map_err(llvm_err)?;
        let wn_nw1 = self.builder.build_int_add(wn_tmp, i64.const_int(1, false), "nw1").map_err(llvm_err)?;
        let wn_nz = self.builder.build_int_compare(IntPredicate::SLT, wn_nw1, i64.const_int(0, false), "nz").map_err(llvm_err)?;
        let wn_nwin = self.builder.build_select(wn_nz, i64.const_int(0, false), wn_nw1, "nwin").map_err(llvm_err)?.into_int_value();
        let wn_res = self.call_rt("atomic_list_create", &[i64.const_int(4, false).into()])?;
        let wn_resv = wn_res.try_as_basic_value().basic().unwrap();
        let wn_ra = self.builder.build_alloca(self.list_type, "wn_ra").map_err(llvm_err)?;
        self.builder.build_store(wn_ra, wn_resv).map_err(llvm_err)?;
        let wn_i = self.builder.build_alloca(i64, "wn_i").map_err(llvm_err)?;
        self.builder.build_store(wn_i, i64.const_int(0, false)).map_err(llvm_err)?;
        let wn_loop = self.context.append_basic_block(wn_fn, "loop");
        let wn_body = self.context.append_basic_block(wn_fn, "body");
        let wn_done = self.context.append_basic_block(wn_fn, "done");
        let _ = self.builder.build_unconditional_branch(wn_loop);
        self.builder.position_at_end(wn_loop);
        let wn_iv = self.builder.build_load(i64, wn_i, "iv").map_err(llvm_err)?.into_int_value();
        let wn_cond = self.builder.build_int_compare(IntPredicate::SLT, wn_iv, wn_nwin, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(wn_cond, wn_body, wn_done);
        self.builder.position_at_end(wn_body);
        let wn_subl = self.call_rt("atomic_list_create", &[wn_wsafe.into()])?;
        let wn_sublv = wn_subl.try_as_basic_value().basic().unwrap();
        let wn_sa = self.builder.build_alloca(self.list_type, "wn_sa").map_err(llvm_err)?;
        self.builder.build_store(wn_sa, wn_sublv).map_err(llvm_err)?;
        let wn_j = self.builder.build_alloca(i64, "wn_j").map_err(llvm_err)?;
        self.builder.build_store(wn_j, i64.const_int(0, false)).map_err(llvm_err)?;
        let wn_iloop = self.context.append_basic_block(wn_fn, "iloop");
        let wn_ibody = self.context.append_basic_block(wn_fn, "ibody");
        let wn_idone = self.context.append_basic_block(wn_fn, "idone");
        let _ = self.builder.build_unconditional_branch(wn_iloop);
        self.builder.position_at_end(wn_iloop);
        let wn_jv = self.builder.build_load(i64, wn_j, "jv").map_err(llvm_err)?.into_int_value();
        let wn_jc = self.builder.build_int_compare(IntPredicate::SLT, wn_jv, wn_wsafe, "jc").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(wn_jc, wn_ibody, wn_idone);
        self.builder.position_at_end(wn_ibody);
        let wn_ep_idx = self.builder.build_int_add(wn_iv, wn_jv, "epi").map_err(llvm_err)?;
        let wn_ep = unsafe { self.builder.build_gep(self.string_type, wn_data, &[wn_ep_idx], "ep").map_err(llvm_err) }?;
        let wn_ev = self.builder.build_load(self.string_type, wn_ep, "ev").map_err(llvm_err)?.into_struct_value();
        let wn_cl = self.builder.build_load(self.list_type, wn_sa, "cl").map_err(llvm_err)?.into_struct_value();
        let wn_ps = self.call_rt("atomic_list_push", &[wn_cl.into(), wn_ev.as_basic_value_enum().into()])?;
        self.builder.build_store(wn_sa, wn_ps.try_as_basic_value().basic().unwrap()).map_err(llvm_err)?;
        let wn_jvi = self.builder.build_int_add(wn_jv, i64.const_int(1, false), "jvi").map_err(llvm_err)?;
        self.builder.build_store(wn_j, wn_jvi).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(wn_iloop);
        self.builder.position_at_end(wn_idone);
        let wn_fat = self.string_type.get_undef();
        let wn_ft = self.builder.build_insert_value(wn_fat, i64.const_int(6, false), 0, "ft").map_err(llvm_err)?;
        let wn_sl = self.builder.build_load(self.list_type, wn_sa, "sl").map_err(llvm_err)?.into_struct_value();
        let wn_sp = self.builder.build_alloca(self.list_type, "wn_sp").map_err(llvm_err)?;
        self.builder.build_store(wn_sp, wn_sl).map_err(llvm_err)?;
        let wn_fv = self.builder.build_insert_value(wn_ft, wn_sp, 1, "fv").map_err(llvm_err)?;
        let wn_rl = self.builder.build_load(self.list_type, wn_ra, "rl").map_err(llvm_err)?.into_struct_value();
        let wn_rps = self.call_rt("atomic_list_push", &[wn_rl.into(), wn_fv.as_basic_value_enum().into()])?;
        self.builder.build_store(wn_ra, wn_rps.try_as_basic_value().basic().unwrap()).map_err(llvm_err)?;
        let wn_ivi = self.builder.build_int_add(wn_iv, i64.const_int(1, false), "ivi").map_err(llvm_err)?;
        self.builder.build_store(wn_i, wn_ivi).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(wn_loop);
        self.builder.position_at_end(wn_done);
        let wn_rt = self.builder.build_load(self.list_type, wn_ra, "wn_rt").map_err(llvm_err)?;
        let _ = self.builder.build_return(Some(&wn_rt));

        // ---- atomic_list_index_of({ptr, i64, i64}, {i64, ptr}) -> i64 ----
        let lio_fn = self.module.add_function("atomic_list_index_of",
            i64.fn_type(&[list_ty.into(), str_ty.into()], false), None);
        let lio_entry = self.context.append_basic_block(lio_fn, "entry");
        self.builder.position_at_end(lio_entry);
        let lio_lst = lio_fn.get_first_param().unwrap().into_struct_value();
        let lio_tgt = lio_fn.get_nth_param(1).unwrap().into_struct_value();
        let lio_data = self.builder.build_extract_value(lio_lst, 0, "data").map_err(llvm_err)?.into_pointer_value();
        let lio_len = self.builder.build_extract_value(lio_lst, 1, "len").map_err(llvm_err)?.into_int_value();
        let lio_i = self.builder.build_alloca(i64, "i").map_err(llvm_err)?;
        self.builder.build_store(lio_i, i64.const_int(0, false)).map_err(llvm_err)?;
        let lio_loop = self.context.append_basic_block(lio_fn, "loop");
        let lio_body = self.context.append_basic_block(lio_fn, "body");
        let lio_nf = self.context.append_basic_block(lio_fn, "notfound");
        let _ = self.builder.build_unconditional_branch(lio_loop);
        self.builder.position_at_end(lio_loop);
        let lio_iv = self.builder.build_load(i64, lio_i, "iv").map_err(llvm_err)?.into_int_value();
        let lio_cond = self.builder.build_int_compare(IntPredicate::SLT, lio_iv, lio_len, "cond").map_err(llvm_err)?;
        let _ = self.builder.build_conditional_branch(lio_cond, lio_body, lio_nf);
        self.builder.position_at_end(lio_body);
        let lio_ep = unsafe { self.builder.build_gep(self.string_type, lio_data, &[lio_iv], "ep").map_err(llvm_err) }?;
        let lio_ev = self.builder.build_load(self.string_type, lio_ep, "ev").map_err(llvm_err)?.into_struct_value();
        let lio_etag = self.builder.build_extract_value(lio_ev, 0, "etag").map_err(llvm_err)?.into_int_value();
        let lio_ttag = self.builder.build_extract_value(lio_tgt, 0, "ttag").map_err(llvm_err)?.into_int_value();
        let lio_teq = self.builder.build_int_compare(IntPredicate::EQ, lio_etag, lio_ttag, "teq").map_err(llvm_err)?;
        let lio_eptr = self.builder.build_extract_value(lio_ev, 1, "eptr").map_err(llvm_err)?.into_pointer_value();
        let lio_tptr = self.builder.build_extract_value(lio_tgt, 1, "tptr").map_err(llvm_err)?.into_pointer_value();
        let lio_ptr_match = self.builder.build_int_compare(IntPredicate::EQ,
            self.builder.build_ptr_to_int(lio_eptr, i64, "").map_err(llvm_err)?,
            self.builder.build_ptr_to_int(lio_tptr, i64, "").map_err(llvm_err)?, "scm").map_err(llvm_err)?;
        let lio_match = self.builder.build_and(lio_teq, lio_ptr_match, "match").map_err(llvm_err)?;
        let lio_ret_match = self.context.append_basic_block(lio_fn, "ret_match");
        let lio_next = self.context.append_basic_block(lio_fn, "next");
        let _ = self.builder.build_conditional_branch(lio_match, lio_ret_match, lio_next);
        self.builder.position_at_end(lio_ret_match);
        let _ = self.builder.build_return(Some(&lio_iv));
        self.builder.position_at_end(lio_next);
        let lio_inc = self.builder.build_int_add(lio_iv, i64.const_int(1, false), "inc").map_err(llvm_err)?;
        self.builder.build_store(lio_i, lio_inc).map_err(llvm_err)?;
        let _ = self.builder.build_unconditional_branch(lio_loop);
        self.builder.position_at_end(lio_nf);
        let _ = self.builder.build_return(Some(&i64.const_int(-1i64 as u64, true)));

        Ok(())
    }
}
